#!/bin/bash


lines=$(grep -e 'HTTP/1.1" 4' -e 'HTTP/1.0" 4' log.txt | cut -f12 -d " "| grep -v '"-"' | grep -v '<a'  | wc -l);
x = 1;

grep -e 'HTTP/1.1" 4' -e 'HTTP/1.0" 4' log.txt | cut -f12 -d" " | cut -c 2-| tr -d [  | sort -k1 | uniq -c | sort -r -k1 -n | head | awk -v x="$x" -v a="$lines"  '{print ++x ". " $2 " -",$1 " -", $1/a*100 "%"}';

