#! /bin/bash

# run this script as "top10 log.txt"

# here comes your solution
# e.g.
lines = $(grep -e 'HTTP/1.1" 4' -e 'HTTP/1.0" 4' log.txt | cut -f12 -d " "| grep -v '"-"' | grep -v '<a'  | wc -l);

for i in `cut -f12 -d" " log.txt | grep -v '"-"' | grep -v '<a' | sort -t" " -k1 | uniq -c | sort -r | head -n 10`;  
do 
	if [[ $i =~ ^[0-9]+$ ]]; then  
		printf "$i -  %0.3f %%" $(echo "($i/$lines)*100" | bc -l); 
	else printf " - $i \n"; fi  ; 
done;
